/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1s5Ig2vRTkt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function container() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-gray-900 text-white py-4 px-6">
        <h1 className="text-2xl font-bold">SuperAcme Attendance</h1>
      </header>
      <main className="flex-1 flex flex-col items-center justify-center gap-8 p-8">
        <div className="w-full max-w-2xl bg-gray-100 dark:bg-gray-800 rounded-lg overflow-hidden">
          <div className="aspect-video relative">
            <span className="w-full h-full object-cover rounded-md bg-gray-100 dark:bg-gray-800" />
            <div className="absolute inset-0 flex items-center justify-center">
              <CameraIcon className="w-12 h-12 text-gray-500 dark:text-gray-400" />
            </div>
          </div>
        </div>
        <Button className="w-full max-w-md" size="lg">
          Take Attendance
        </Button>
      </main>
    </div>
  )
}

function CameraIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z" />
      <circle cx="12" cy="13" r="3" />
    </svg>
  )
}
